# Generated by Django 4.1.7 on 2023-02-28 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rockets_bdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите описание проекта', max_length=200, null=True)),
                ('data_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_rockets', models.SmallIntegerField()),
                ('kolichestvo_amort', models.SmallIntegerField()),
                ('zhestkost_amort', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
