# Generated by Django 4.1.7 on 2023-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockets_bdf',
            name='start_rockets',
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='start_rocket',
            field=models.PositiveSmallIntegerField(help_text='Введите 0, если старт подводный, 1 - наземный', null=True),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='kolichestvo_amort',
            field=models.PositiveSmallIntegerField(help_text='Введите число от 2 до 5'),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='zhestkost_amort',
            field=models.DecimalField(decimal_places=2, help_text='(с точностью до сотых) zhestkost_amort * 10^7', max_digits=12),
        ),
    ]
