# Generated by Django 4.1.7 on 2023-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0002_remove_rockets_bdf_start_rockets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='X1',
            field=models.DecimalField(decimal_places=1, default=1, help_text='от нижнего края ракеты до верхнего (первого) пояса амортизации в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X2',
            field=models.DecimalField(decimal_places=1, default=1, help_text='от нижнего края ракеты второго пояса амортизации в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
    ]
