# Generated by Django 4.1.7 on 2023-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0003_rockets_bdf_x1_rockets_bdf_x2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='V_sredy',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='d0',
            field=models.DecimalField(decimal_places=2, default=1, help_text='с точностью до сотых', max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='X1',
            field=models.DecimalField(decimal_places=1, help_text='от нижнего края ракеты до верхнего (первого) пояса амортизации в м с точностью до десятых', max_digits=6),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='X2',
            field=models.DecimalField(decimal_places=1, help_text='от нижнего края ракеты второго пояса амортизации в м с точностью до десятых', max_digits=6),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='kolichestvo_amort',
            field=models.PositiveSmallIntegerField(help_text='Введите число от 1 до 5'),
        ),
    ]
