# Generated by Django 4.1.7 on 2023-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0004_rockets_bdf_v_sredy_rockets_bdf_d0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='L',
            field=models.DecimalField(decimal_places=1, default=1, help_text='с точностью до десятых', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='m',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в кг.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='V_sredy',
            field=models.DecimalField(decimal_places=1, help_text='м/с', max_digits=4),
        ),
    ]
