# Generated by Django 4.1.7 on 2023-03-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0005_rockets_bdf_l_rockets_bdf_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='Lg',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='Lo',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X_cy',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X_dy',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X_gch',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='Xg',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='Xo',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='m_cy',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в кг.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='m_dy',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в кг.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='m_gch',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в кг.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='mg',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в кг.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='mo',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в кг.', max_digits=12),
            preserve_default=False,
        ),
    ]
