# Generated by Django 4.1.7 on 2023-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0006_rockets_bdf_lg_rockets_bdf_lo_rockets_bdf_x_cy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='koeff_puass1',
            field=models.DecimalField(decimal_places=2, default=1, help_text='с точностью до сотых', max_digits=6, verbose_name='Коэффициент Пуассона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='koeff_puass2',
            field=models.DecimalField(decimal_places=2, default=1, help_text='с точностью до сотых', max_digits=6, verbose_name='Коэффициент Пуассона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='modul_unga1',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12, verbose_name='Задание свойства материала ракеты. Модуль Юнга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='modul_unga2',
            field=models.DecimalField(decimal_places=1, default=1, help_text='в м с точностью до десятых', max_digits=12, verbose_name='Задание свойства материала контейнера. Модуль Юнга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='plotnost2',
            field=models.DecimalField(decimal_places=2, default=1, help_text='с точностью до сотых', max_digits=6, verbose_name='Плотность материала контейнера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t',
            field=models.DecimalField(decimal_places=3, default=1, help_text='с точностью до тысячных', max_digits=6, verbose_name='Время выхода ракеты из контейнера в секундах'),
            preserve_default=False,
        ),
    ]
