# Generated by Django 4.1.7 on 2023-03-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0007_rockets_bdf_koeff_puass1_rockets_bdf_koeff_puass2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='P1',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее первому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p1',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для первой точки'),
            preserve_default=False,
        ),
    ]
