# Generated by Django 4.1.7 on 2023-03-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0008_rockets_bdf_p1_rockets_bdf_t_p1'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='P10',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее десятому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P11',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее одиннадцатому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P12',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее двенадцатому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P13',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее тринадцатому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P2',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее второму времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P3',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее третьему времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P4',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее четвертому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P5',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее пятому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P6',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее шестому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P7',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее седьмому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P8',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее восьмому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P9',
            field=models.IntegerField(default=1, help_text="в Н (в диапазоне от 100 до 99'999'999 Н)", verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите соответствующее девятому времени значение тяги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p10',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для десятой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p11',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для одиннадцатой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p12',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для двенадцатой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p13',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для тринадцатой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p2',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для второй точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p3',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для третьей точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p4',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для четвертой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p5',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для пятой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p6',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для шестой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p7',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для седьмой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p8',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для восьмой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p9',
            field=models.DecimalField(decimal_places=2, default=1, help_text='в секундах с точностью до сотых', max_digits=6, verbose_name='Задание тяги двигателя (13 точек) в зависисмости от времени. Введите время для девятой точки'),
            preserve_default=False,
        ),
    ]
