# Generated by Django 4.1.7 on 2023-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0009_rockets_bdf_p10_rockets_bdf_p11_rockets_bdf_p12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='N',
            field=models.DecimalField(decimal_places=1, default=1, help_text='(с шагом k = 0.1)', max_digits=12, verbose_name='Количество узлов ракеты'),
            preserve_default=False,
        ),
    ]
